export const SET_PLACEHOLDER_SPINNER_ANIMATION = 'SET_PLACEHOLDER_SPINNER_ANIMATION'

// joint style
export const SET_JOINT_STYLE = 'SET_JOINT_STYLE'

export const JOINT_STYLE_THROUGH = 'JOINT_STYLE_THROUGH'

export const JOINT_STYLE_HALF_BLIND = 'JOINT_STYLE_HALF_BLIND'
export const SET_HALF_BLIND_JOINT_OFFSET = 'SET_HALF_BLIND_JOINT_OFFSET'

// edge style
export const SET_EDGE_STYLE = 'SET_EDGE_STYLE'
export const EDGE_STYLE_HALF_PIN = 'EDGE_STYLE_HALF_PIN'
export const EDGE_STYLE_HALF_TAIL = 'EDGE_STYLE_HALF_TAIL'

// joint dimensions
export const SET_PIN_BOARD_THICKNESS = 'SET_PIN_BOARD_THICKNESS'
export const SET_TAIL_BOARD_THICKNESS = 'SET_TAIL_BOARD_THICKNESS'
export const SET_JOINT_LENGTH = 'SET_JOINT_LENGTH'

// pin style
export const SET_PIN_LAYOUT_STYLE = 'SET_PIN_LAYOUT_STYLE'

export const PIN_LAYOUT_STYLE_SIMPLE = 'PIN_LAYOUT_STYLE_SIMPLE'
export const SET_SIMPLE_PIN_LAYOUT_PIN_COUNT = 'SET_SIMPLE_PIN_LAYOUT_PIN_COUNT'
export const SET_SIMPLE_PIN_LAYOUT_WIDTH = 'SET_SIMPLE_PIN_LAYOUT_WIDTH'
export const SET_SIMPLE_PIN_LAYOUT_SLOPE = 'SET_SIMPLE_PIN_LAYOUT_SLOPE'

export const PIN_LAYOUT_STYLE_CUSTOM = 'PIN_LAYOUT_STYLE_CUSTOM'
export const ADD_CUSTOM_PIN = 'ADD_CUSTOM_PIN'
export const UPDATE_CUSTOM_PIN = 'UPDATE_CUSTOM_PIN'
export const REMOVE_CUSTOM_PIN = 'REMOVE_CUSTOM_PIN'